### ISSUE TITLE
No scrolling

### ISSUE THREAD

**Issue by AnthonyLeinebo** [h669782/Kledeli#1]
On mobile view, you can't scroll down the page. In other words, the page content is cut off. Bug not tested on desktop view.

**Comment by h669782** [comment]
Changed overflow from hidden to auto, in the styles.css file. This change applies for all pages. Bug fixed.

**Comment by AnthonyLeinebo** [comment]
Changed overflow from hidden to auto, in the styles.css file. This change applies for all pages. Bug fixed.
